---
title: "ROC plots for prediction"
author: "Brian Lu"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview


**Objective:** Plot ROC curves for subtype prediction random forest model.

# Environment set up

```{r}
library(tidyverse)
library(pROC)
```

Set root directory

```{r}
here::i_am("README.md")
```

Import all available records for calculating HOMA1 estimates between 2010-2019.

```{r}

import_dir <- "/data/user/brianlu/projects/precision_diabetes/cluster_prediction/exports/models"

data <- read_csv(file.path(import_dir, "roc_values.csv"))

```

# Plot ROC

```{r}
ggplot_roc <- function(pred, scores, auc_digits = 1, save = F, save_path, width = 1.5, height = 1.5, units = "in", dpi = 600){
  # Plot ROC in ggplot
  
  rocobj <- roc(pred, scores,
                main="Confidence intervals", 
                percent=TRUE,
                ci=TRUE, # compute AUC (of AUC by default)
                of = "auc",
                auc=TRUE,
                direction = "<") # print the AUC (will contain the CI)
  
  auc <- tibble(auc = round(rocobj$auc, auc_digits),
                ci_lower = round(rocobj$ci, auc_digits)[1],
                ci_upper = round(rocobj$ci, auc_digits)[3])
  
  gg <- ggroc(rocobj) + 
    theme_classic(base_size = 7) + 
    # geom_abline(intercept = 100, slope = -1, color = "grey") + 
    #annotate("text", x = 40, y = 40, label = glue::glue("AUC (95% CI):\n{auc}% ({ci_lower}-{ci_upper}%)"), size = 1.5) +
    labs(x = "Specificity (%)", y = "Sensitivity (%)")
  
  if (save){
    ggsave(save_path, plot = gg, width = width, height = height, units = units, dpi = dpi)
  }
  
  return(list(gg, auc))
}

export_dir <- here::here("exports", "UAB")

auc_out <- list()
clusters <- c("SAID", "SIDD", "SIRD", "MOD", "MARD")
for (c in clusters){
  roc_out <- ggplot_roc(data[[c]], 
                        data[[paste(c, "score", sep = "_")]], 
                        save = T,
                        save_path = file.path(export_dir, paste("prediction", tolower(c), "roc.tiff", sep = "_")))
  auc_out[[c]] <- roc_out[2]
}

auc_out <- auc_out %>%
  bind_rows() %>%
  mutate(clusters = clusters) %>%
  relocate(clusters)

write_csv(auc_out, file.path(export_dir, "prediction_roc_auc.csv"))

```

# Session information

```{r}
sessionInfo()
```

